### ISSUE TITLE
Deck not working properly on Internet explorer

### ISSUE THREAD

**Issue by renarsmz** [imakewebthings/deck.js#119]
There seems to be a strange problem with Deck.js on every IE browser (9, 8, 7). Slides are not positioning properly (content not centering, no background). I used original boilerplate.html file, no modifications. It works fine on Chrome and Firefox. I have this problem only with the downloadable version available from this site https://github.com/imakewebthings/deck.js/zipball/stable.
Your online demo from http://imakewebthings.com/deck.js/ works fine on IE. 

Can someone help me please? I really need to get it working on IE.

![Untitled](https://f.cloud.github.com/assets/3667028/183887/9d957a6e-7cbf-11e2-98c0-269f2428f707.jpg)

**Comment by johnjd** [comment]
The look and feel of deckjs presentation is different from the way it renders in Mozilla FireFox and Google Chrome.
Specifically, when I specify vertical sliding, (<link rel="stylesheet" media="screen" href="lib/deck.js/themes/transition/vertical-slide.css">) - in IE9, the horizontal slider arrows are render (instead of vertical slider). 
(However, the horizontal and vertical sliders are rendered properly in Mozilla FireFox and Google Chrome.)
